### ISSUE TITLE
Bug: not working with markdown_extensions : md_in_html

### ISSUE THREAD

**Issue by kim5566** [backstage/techdocs-cli#139]
# Bug: Should remove trailing whitespace in HTML tags.

I have markdown content inside HTML tag. 
For example, the following:
```
<div markdown="1">

This is a *Markdown* Paragraph.

</div>
```
...is rendered as:
```
<div>
<p>This is a <em>Markdown</em> Paragraph.</p>
</div>
```
### However, it breaks when there's trailing whitespace
For example, the following:
```
<div markdown = "1">

This is a *Markdown* Paragraph.

</div>
```
...is rendered as:
```
<div>
<p>= "1"&gt;</p>
<p>This is a <em>Markdown</em> Paragraph.</p>
</div>
```
# Expected behavior: 

Should be rendered as:
```
<div>
<p>This is a <em>Markdown</em> Paragraph.</p>
</div>
```

# Context:
techdocs-cli --version 0.7.0

# Note
This seems not to be a bug of mkdocs. If I run `mkdocs:serve` (version 1.2.2), I get the expected behaviour. 
Only happens if I run `techdocs-cli serve:mkdocs`

**Comment by emmaindal** [comment]
Hi @kim5566, thanks for opening this issue, the techdocs-cli uses https://github.com/backstage/mkdocs-techdocs-core and using the techdocs-core plugin I can reproduce the bug you have reported, but can you open the issue there instead? So that we keep the issue in the repo where it needs to be looked into. Thanks in advance!
