### ISSUE TITLE
Shouldn't the `dist-types` folders be on the gitignore?

### ISSUE THREAD

**Issue by Fox32** [backstage/techdocs-cli#64]
Shouldn't the `dist-types` folders be on the gitignore? I think you shouldn't check them in. Or is there a special reason to check them in here?

**Comment by OrkoHunter** [comment]
I remember removing them in [this PR](https://github.com/backstage/techdocs-cli/pull/20) but had to add them back https://github.com/backstage/techdocs-cli/pull/23

I believe it's because of how this repo is structured, a top level mono-repo (cli repository) containing a package (cli) and another mono-repo (backstage) with two packages (app and backend).

**Comment by andrewthauer** [comment]
This should be fixed by #89

**Comment by Fox32** [comment]
Thanks @andrewthauer
