### ISSUE TITLE
techdocs-cli serve command shows warning about building documentation

### ISSUE THREAD

**Issue by andrewthauer** [backstage/techdocs-cli#78]
The following warning shows up when previewing documentation.

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/6507159/124122947-aa9d5100-da44-11eb-80cc-168930e337f2.png">

I see the same thing in backstage as well and suspect it's related to recent backstage package dependency updates. I haven't looked into the underlying issue yet to know if it's in the CLI or perhaps `@backstage/plugin-techdocs` (more likely). However, this particular warning does not seem like it should be displayed here. Might require maybe added a setting to disable it the `techdocs-cli` can use.

**Comment by dhenneke** [comment]
I think the cause is that the return value of this function changed: https://github.com/backstage/techdocs-cli/blob/21053a5130f9a0dfd8ce14a7d487de8daf5d4f22/packages/embedded-techdocs/packages/app/src/apis.ts#L97-L101

It was `syncEntityDocs(entityId: EntityName): Promise<boolean>;`, but in https://github.com/backstage/backstage/pull/5975 I changed it to `syncEntityDocs(entityId: EntityName): Promise<SyncResult>;`.

The needed change is probably:
```diff
  async syncEntityDocs(_: EntityName) { 
    // this is just stub of this function as we don't need to check if docs are up to date, 
    //we always want to retrigger a new build 
-   return true; 
+   return 'cached';
  } 
```

However, I would not expect this to result in a timeout state but more in an error state.
