### ISSUE TITLE
npx command failing

### ISSUE THREAD

**Issue by lucasmdrs** [backstage/techdocs-cli#86]
I'm trying to execute `npx @techdocs/cli generate --verbose` command but is failing with:
```
info: Using source dir /path/to/repos/techdocs-cli
info: Will output generated files in /path/to/repos/techdocs-cli/site
warn: The 'techdocs.generators.techdocs' configuration key is deprecated and will be removed in the future. Please use 'techdocs.generator' instead.
info: Generating documentation...
Failed to generate docs from /path/to/repos/techdocs-cli into /path/to/repos/techdocs-cli/site with error Cannot read property 'info' of undefined
```

Tried with args `--verbose` `--no-docker` and got the same result.

--- 
**Repository used for docs:** github.com/backstage/techdocs-cli
**Versions:**
```
$ npx @techdocs/cli --version
0.4.1

$ npx --version
6.14.13

$ node --version
v14.17.3
```

The error does not occur when building from master branch

**Comment by andrewthauer** [comment]
This is related to a new `logger` option added to `@backstage/techdocs-common` https://github.com/backstage/backstage/pull/6341/files#diff-ddd013876d02c04e8ddaad2ac791a0310e9694046c3f8db9235afd648cd86054R64. This was a breaking change but only added bumped as a patch. The existing `techdocs-cli` works fine when you clone it, but running npx will pull the latest minor version of `techdocs-common` and this error starts occurring.

I can include a fix for this in my PR for #81. However, this highlights that it's very easy to overlook a breaking change since techdocs-common is in the core backstage repo and tests won't catch this.
